// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkeTqLzgS6kkbSAzToEdI85ZxPNquuqFo',
    appId: '1:571231310225:web:584cf853bbeeea5044ca30',
    messagingSenderId: '571231310225',
    projectId: 'adventurize-ffaa1',
    authDomain: 'adventurize-ffaa1.firebaseapp.com',
    databaseURL: 'https://adventurize-ffaa1-default-rtdb.firebaseio.com',
    storageBucket: 'adventurize-ffaa1.appspot.com',
    measurementId: 'G-1XCN294V9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAepDC8E75GZtdzddQcweeNwV4iWLcO2Ic',
    appId: '1:571231310225:android:2cccd19861e5468f44ca30',
    messagingSenderId: '571231310225',
    projectId: 'adventurize-ffaa1',
    databaseURL: 'https://adventurize-ffaa1-default-rtdb.firebaseio.com',
    storageBucket: 'adventurize-ffaa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBdRdJJ6Vlcef5pq9Mc_VeRraVoCcNnQ',
    appId: '1:571231310225:ios:9994ba24582a6e7544ca30',
    messagingSenderId: '571231310225',
    projectId: 'adventurize-ffaa1',
    databaseURL: 'https://adventurize-ffaa1-default-rtdb.firebaseio.com',
    storageBucket: 'adventurize-ffaa1.appspot.com',
    iosBundleId: 'br.com.adventurize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBdRdJJ6Vlcef5pq9Mc_VeRraVoCcNnQ',
    appId: '1:571231310225:ios:a1243cb8aad7f2a244ca30',
    messagingSenderId: '571231310225',
    projectId: 'adventurize-ffaa1',
    databaseURL: 'https://adventurize-ffaa1-default-rtdb.firebaseio.com',
    storageBucket: 'adventurize-ffaa1.appspot.com',
    iosBundleId: 'br.com.adventurize.RunnerTests',
  );
}
